name: hello-docker
author: liraz
description: sends greeting to ua user

inputs:
  who_to_greet:
    description: "who to greet?"
    #required: true
    default: word
outputs:
  time:
    description: "time of the greeting"
  name:
    description: "I Greet you"


runs:
  using: docker
  image: 'Dockerfile'
  args:
    - "${{inputs.who_to_greet}}"
  env:
    HELLO: word
    NAME: '${{inputs.who_to_greet}}'
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os == 'Linux'
