name: Dynamic-Matrix1.yml
on:
  workflow_dispatch:
    inputs:
      os:
        description: An os reuired
        type: string
        default: "windows-latest,ubuntu-latest"
      node-version:
        description: Node version
        default: "14,15,16"
        type: string

jobs:
  prepare-metrix:
    runs-on: ubuntu-latest
    outputs:
      os: "${{steps.matrix-arrays.outputs.OS}}"
      node: "${{steps.matrix-arrays.outputs.NODE}}"
    steps:
      - run: |
          echo "OS=${{inputs.os}}" >> "$GITHUB_OUTPUT" 
          echo "NODE=${{inputs.node-version}}" >> "$GITHUB_OUTPUT"
        id: matrix-arrays
      - run: echo "step-output=value" >> "$GITHUB_OUTPUT"
        id: step-1
      - run: echo "step-output=value 2" >> "$GITHUB_OUTPUT"
        id: step-2
      - run: |
          echo "${{steps.step-1.outputs.step-output}}"
          echo "${{steps.step-2.outputs.step-output}}"

  node-matrix:
    needs: prepare-metrix
    strategy:
      matrix:
        os: ${{needs.prepare-metrix.outputs.os}}
        node-version: ${{needs.prepare-metrix.outputs.node}}

    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v