name: Dynamic-Matrix.yml
on:
  workflow_dispatch:
    inputs:
      os:
        description: An os reuired
        type: string
        default: "windows-latest,ubuntu-latest"
      node-version:
        description: Node version
        default: "14,15,16"
        type: string

jobs:
  prepar-metrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "step-output=value" >> $Github.output
        id: step-1
      - run: echo "step-output=value 2" >> $Github.output
        id: step-2
      - run: | 
         echo ${{steps.step-1.outputs.step-output}}
         echo ${{steps.step-2.outputs.step-output}}

  node-matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 14, 15, 16 ]

    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
