name: repositery events
on:
  push:
  pull_request:
    types: [opened, assigned, synchronize, reopened]
  issues:
    types: [opened]

jobs:
  chekout-test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo $GITHUB_SHA 
          echo $GITHUB_REF
      - uses: actions/checkout@v5.0.0
