name: Simple action docker
on: push

jobs:
  CHecout-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: greeting
        id: greeting
        uses: ./.github/actions/hello-docker
        with:
          who_to_greet: 'the creator'
      - name: Display the man of the greeting
        run: |
          echo "I Greet you: '${{ steps.greeting.outputs.name }}' On: '${{ steps.greeting.outputs.time }}'"
