name: Variables and Secrets
on: [push]

jobs:
  decrypt-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          pwd
          ls -la
          ls -la .github/workflows

      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir -p "$HOME/secrets"
          gpg --quiet --batch --yes \
            --decrypt \
            --passphrase="$PASSPHRASE" \
            --output "$HOME/secrets/secret.json" \
            ".github/workflows/secret.json.gpg"

      # DON'T print secrets in real life; left here disabled
      - name: View Encrypted File Content (NEVER DO THIS)
        if: ${{ false }}
        run: cat "$HOME/secrets/secret.json"

  log-vars:
    environment: staging
    runs-on: ${{ vars.JOBS_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: ${{ env.BOOLEAN_SECRET == 'true' }}
        run: echo "I ran"

      - name: Log Vars
        run: |
          echo "JOBS_RUNNER (vars): ${{ vars.JOBS_RUNNER }}"
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
